# This is a generated file. Not intended for manual editing.
services:
  client:
    build:
      context: "C:\\MyProjects\\Wallet.ru-Test-task\\TestTask.Client"
      dockerfile: "Dockerfile"
      target: "build-env"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/../../../Users/UserD/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/8.0.12/tools/blazor-devserver.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "testtask.client:dev"
    ports: []
    volumes:
    - "C:\\Users\\UserD\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\MyProjects\\Wallet.ru-Test-task\\TestTask.Client:/app:rw"
    - "C:\\MyProjects\\Wallet.ru-Test-task:/src:rw"
    working_dir: "/app"
  server:
    build:
      context: "C:\\MyProjects\\Wallet.ru-Test-task\\TestTask.Server"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/TestTask.Server.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "testtask.server:dev"
    ports: []
    volumes:
    - "C:\\Users\\UserD\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\MyProjects\\Wallet.ru-Test-task\\TestTask.Server:/app:rw"
    - "C:\\MyProjects\\Wallet.ru-Test-task:/src:rw"
    working_dir: "/app"
