services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WalletRuTestTask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./TestTask.Server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    ports:
      - "7204:8080"
    depends_on:
      postgres:
       condition: service_healthy
    networks:
      - app-network

  client:
    build:
      context: ./TestTask.Client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "7102:80"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge